# Generated by Django 3.2.20 on 2024-02-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0009_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapmapp.pet'),
        ),
    ]
