# Generated by Django 3.2.20 on 2024-02-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0010_userpayment_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateofbirth',
        ),
        migrations.DeleteModel(
            name='Userpayment',
        ),
    ]
