# Generated by Django 3.2.20 on 2024-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0011_auto_20240217_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
