# Generated by Django 3.2.20 on 2024-02-17 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0012_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('datetime', models.TextField(default='empty')),
                ('order_id_data', models.TextField(default='empty')),
                ('payment_id_data', models.TextField(default='empty')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.pet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
