# Generated by Django 3.2.20 on 2024-02-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0013_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapmapp.userprofile'),
        ),
    ]
