# Generated by Django 3.2.20 on 2024-02-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0014_auto_20240217_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpayment',
        ),
    ]
