# Generated by Django 3.2.20 on 2024-02-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0016_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpayment',
        ),
    ]
