# Generated by Django 3.2.20 on 2024-02-18 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0020_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
