# Generated by Django 3.2.20 on 2024-02-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0021_auto_20240218_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpayment',
        ),
    ]
