# Generated by Django 3.2.20 on 2024-02-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0023_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpayment',
        ),
    ]
