# Generated by Django 3.2.20 on 2024-02-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0026_userpayment_aquarium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
