# Generated by Django 3.2.20 on 2024-02-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0027_userpayment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('dealer_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_rating', models.IntegerField()),
                ('product_review', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.userpayment')),
            ],
        ),
    ]
