# Generated by Django 3.2.20 on 2024-02-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0036_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
