# Generated by Django 3.2.20 on 2024-02-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0038_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_name',
        ),
    ]
