# Generated by Django 3.2.20 on 2024-02-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0039_remove_review_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
