# Generated by Django 3.2.20 on 2024-02-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0041_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_aqu', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('review_text_aqu', models.TextField(null=True)),
                ('created_at_aqu', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aapmapp.aquarium')),
                ('dealer_aqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquarium_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
