# Generated by Django 3.2.20 on 2024-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0043_deliveryman'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_delivery_man',
            field=models.BooleanField(default=False),
        ),
    ]
