# Generated by Django 3.2.20 on 2024-02-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0044_dealer_is_delivery_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_delivery_man',
        ),
    ]
