# Generated by Django 3.2.20 on 2024-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0045_remove_dealer_is_delivery_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment_aquarium',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
