# Generated by Django 3.2.20 on 2024-03-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0048_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteditem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SelectedItem',
        ),
    ]
