# Generated by Django 3.2.20 on 2024-03-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0049_auto_20240315_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.deliveryman')),
            ],
        ),
    ]
