# Generated by Django 3.2.20 on 2024-04-03 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0051_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.deliveryman')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.userpayment_aquarium')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.aquarium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.deliveryman')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.userpayment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.deliveryman')),
            ],
        ),
    ]
