# Generated by Django 3.2.20 on 2024-04-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0053_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment1',
            name='order',
        ),
    ]
