# Generated by Django 3.2.20 on 2024-04-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0054_auto_20240404_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aapmapp.userpayment'),
        ),
    ]
