# Generated by Django 3.2.20 on 2024-04-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0055_deliveryassignment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='payment',
        ),
    ]
