# Generated by Django 3.2.20 on 2024-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0056_remove_deliveryassignment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='order_id',
            field=models.TextField(default='empty'),
        ),
    ]
