# Generated by Django 3.2.20 on 2024-04-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0057_deliveryassignment_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapmapp.deliveryassignment')),
            ],
        ),
    ]
