# Generated by Django 3.2.20 on 2024-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0058_deliveryotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment1',
            name='order_id',
            field=models.TextField(default='empty'),
        ),
    ]
